### ISSUE TITLE
When are going to release the code?

### ISSUE THREAD

**Issue by nanguoshun** [deep-spin/understanding-spigot#1]
Dear Mihaylova,

I am very interested in your work. May I know why you are going to release the code?

Thanks a lot!

Guoshun

**Comment by tsvm** [comment]
Hi, thanks for your interest in our work! 

I added the code. 

I need to improve the README, in order to make it easier to work with, so if you have any questions, don't hesitate to ask.

**Comment by nanguoshun** [comment]
Thanks Mihaylova！
